name: Composite action upload coverage
description: Composite action upload coverage
inputs:
  unique_body_msg:
    description: Unique body message
    required: true
  body:
    description: Body message
    required: true


runs:
  using: "composite"
  steps:

    - name: Find Comment
      if: inputs.use_coverage && inputs.upload_coverage
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ inputs.unique_body_msg }}
        direction: first

    - name: Create or update coverage to PR comment
      if: inputs.use_coverage && inputs.upload_coverage
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ${{ inputs.unique_body_msg }}
          ${{ inputs.body }}
          ${{ steps.jest-tests.outputs.coverage_content }}
        edit-mode: replace