name: Composite action save Python virtual environment
description: Composite action to save Python virtual environment
inputs:
  virtual_environment_path:
    description: Path to the virtual environment.
    required: false
    default: ".venv"
  requirements_paths:
    description: Space separeted list of requirements files. They will be used to compute the hash for the cache key.
    required: true
  git_reference:
    description: A git reference (name of the branch, reference to the PR) that will be used to build the cache key.
    required: false
    default: ${{ github.ref_name }}

runs:
  using: "composite"
  steps:
    - name: Compute requirements files SHA256 hash
      id: compute_requirements_files_sha256_hash
      uses: ./.github/actions/misc/compute_files_hash
      with:
        file_paths: ${{ inputs.requirements_paths }}

    - name: Cache virtual environment
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.virtual_environment_path }}
        key: ${{ inputs.git_reference }}-venv-${{ steps.compute_requirements_files_sha256_hash.outputs.computed_hash }}