repos:
-   repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        files: backend
        args: ["-c", "configurations/python_linter/.bandit.yaml"]

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      exclude: docs/conf.py
      files: backend
      args: ["--config", "configurations/python_linter/.flake8"]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: backend
        args: ["--settings-path", "configurations/python_linter/.isort.cfg", "--profile", "black", "--filter-files", "--skip", "venv"]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--config", "configurations/python_linter/.black"]