name: Composite action node linter
description: Composite action node linter
inputs:
  working_directory:
    description: Path to the package.json file
    required: true


  use_eslint:
    description: Use eslint formatter
    required: true

  use_prettier:
    description: Use prettier formatter
    required: true

  use_stylelint:
    description: Use stylelint formatter
    required: true

  check_packages_licenses:
    description: Check if npm packages have a valid license.
    required: true

runs:
  using: "composite"
  steps:
    - name: Lint with eslint
      if: ${{ inputs.use_eslint }}
      run: |
        npm run lint
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Lint with prettier
      if: ${{ inputs.use_prettier }}
      run: |
        npm run prettier:check
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Lint with stylelint
      if: ${{ inputs.use_stylelint }}
      run: |
        npm run lint-sass
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Collect packages licenses
      if: inputs.check_packages_licenses
      run: |
        echo '{"name":"", "license":""}' > fmt.json
        npx -y license-checker@25.0.1 --csv --production --excludePrivatePackages --customPath fmt.json | cut -d, -f2,3 | tail -n +2 > licenses.csv
        cat licenses.csv
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Check packages licenses
      if: inputs.check_packages_licenses
      id: license_check_report
      continue-on-error: true
      uses: pilosus/action-pip-license-checker@v0.6.2
      with:
        requirements: ${{ inputs.requirements_path }}
        external: ${{ inputs.working_directory }}/licenses.csv
        external-format: csv
        table-headers: true
        fail: 'StrongCopyleft,NetworkCopyleft,Error'
        fails-only: true