name: Composite action create Python docs requirements file
description: Composite action to create Python docs requirements file
inputs:
  install_from:
    description: Directory that must be used to install the packages
    required: false
    default: .
  project_docs_requirements_file:
    description: An additional project docs requirements file
    required: false
  django_settings_module:
    description: Path to the django settings file
    required: false
  check_docs_directory:
    description: Check docs using rstcheck inside this directory
    required: false

runs:
  using: "composite"
  steps:
    - name: Create requirements-docs.txt
      run: |
        echo > requirements-docs.txt
        if [[ -n '${{ inputs.check_docs_directory }}' ]]; then
          echo "rstcheck[sphinx]" >> requirements-docs.txt 
          echo "sphinx==7.2.6" >> requirements-docs.txt
          echo "sphinx_rtd_theme==1.3.0" >> requirements-docs.txt
          echo "sphinxcontrib-spelling==8.0.0" >> requirements-docs.txt
          if [[ -n '${{ inputs.django_settings_module }}' ]]; then
            echo "sphinxcontrib-django2==1.9" >> requirements-docs.txt
          fi
          if [[ -z '${{ inputs.project_docs_requirements_file }}' ]];then
            cat $(echo ${{ inputs.project_docs_requirements_file }}) >> requirements-docs.txt
          fi
        fi
      shell: bash
      working-directory: ${{ inputs.install_from }}