name: Composite action install APT requirements
description: Composite action to install APT requirements
inputs:
  requirements_file:
    description: Requirements file
    required: true

# TODO scomporre questa action in due:
# - save apt cache
# - restore apt cache
runs:
  using: "composite"
  steps:
    - name: Compute apt requirements file SHA256 hash
      id: compute_apt_requirements_file_sha256_hash
      uses: ./.github/actions/misc/compute_files_hash
      with:
        file_paths: ${{ inputs.requirements_file }}
    
    # Vital to be able to restore cache
    # If write permission is not set, a permissions error will be raised
    - name: Modification to /var/cache/apt/archives permissions
      run: |
        sudo chmod a+w /var/cache/apt/archives
      shell: bash

    - uses: actions/cache/restore@v4
      id: restore_cache_from_parent_branch
      with:
        path: /var/cache/apt/archives/*.deb
        key: ${{ github.base_ref }}-${{ steps.compute_apt_requirements_file_sha256_hash.outputs.computed_hash }}
    
    - uses: actions/cache/restore@v4
      id: restore_cache_from_current_branch
      if: steps.restore_cache_from_parent_branch.outputs.cache-hit != 'true'
      with:
        path: /var/cache/apt/archives/*.deb
        key: ${{ github.ref_name }}-${{ steps.compute_apt_requirements_file_sha256_hash.outputs.computed_hash }}

    - name: Refresh repositories
      if: >
        steps.restore_cache_from_parent_branch.outputs.cache-hit != 'true' &&
        steps.restore_cache_from_current_branch.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
      shell: bash

    - name: Install requirements
      run: |
        sudo apt-get install -y --no-install-recommends $(tr '\n' ' ' < ${{ inputs.requirements_file }})
      shell: bash
    
    - uses: actions/cache/save@v4
      id: cache_apt_requirements_for_current_branch
      if: >
        steps.restore_cache_from_parent_branch.outputs.cache-hit != 'true' && 
        steps.restore_cache_from_current_branch.outputs.cache-hit != 'true'
      with:
        path: /var/cache/apt/archives/*.deb
        key: ${{ github.ref_name }}-${{ steps.compute_apt_requirements_file_sha256_hash.outputs.computed_hash }}