name: CI

on:
  pull_request:
    branches:
      - master
      - main
      - develop
      - dev

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    uses: ./reusable_workflows/detect-changes.yml
    with:
      backend_directories: backend
      frontend_directories: frontend


  node:
    uses: ./reusable_workflows/node.yml
    with:
      working_directory: test/node_test

      use_eslint: true
      use_prettier: true
      use_stylelint: true

      check_packages_licenses: true
      use_jest: true
      use_coverage: true
      upload_coverage: true

      node_versions: >-
        ["16"]


  python:
     uses: ./reusable_workflows/python.yml
     secrets: inherit
     with:
      working_directory: test/python_test
      use_black: false
      use_isort: true
      use_flake8: true
      use_pylint: true
      use_bandit: false
      use_autoflake: true


      requirements_path: test/python_test/requirements.txt
      packages_path: test/python_test/packages.txt
      django_settings_module: python_test.settings

      check_migrations: true
      check_requirements_licenses: true
      check_docs_directory: test/docs
      check_dockerfile: Dockerfile

      use_postgres: false
      use_memcached: false
      use_elastic_search: false
      use_rabbitmq: true
      use_mongo: false
      use_celery: true

      celery_app: python_test.celery
      celery_queues: default

      use_coverage: true
      upload_coverage: true
      tags_for_slow_tests: main
      tags_for_manual_tests: manual

      custom_command: whoami; ls -la
      env: >-
        {"KEY": "VALUE"}
      python_versions: >-
        ["3.9"]

  release_and_tag:
    uses: ./reusable_workflows/release_and_tag.yml
    secrets: inherit
    with:
      publish_on_pypi: false
      publish_on_test_pypi: false
      publish_on_npm: false
