name: Certego Python Library CI

on:
  push:
    branches:
      - master
      - main
      - develop
      - dev
  pull_request:
    branches:
      - master
      - main
      - develop
      - dev

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python_linters:
    uses: certego/.github/.github/workflows/python_linter.yml@main
    with:
      working_directory: backend
      use_black: true
      use_isort: true
      use_flake8: true
      use_pylint: true
      use_bandit: true
      python_versions: >-
        ["3.10", "3.9", "3.8"]

  python_tests:
     uses: certego/.github/.github/workflows/python_tests.yml@main
     with:
      working_directory: backend
      requirements_path: backend/requirements.txt
      packages_path: test/python_test/packages.txt
      python_versions: >-
        ["3.10", "3.9", "3.8"]

      custom_command: whoami; ls -la

      use_postgres: false
      use_memcached: false
      use_elastic_search: false

      use_coverage: true
      use_pytest: false
      use_unittest: false
