name: Certego CI

on:
  pull_request:
    branches:
      - master
      - main
      - develop
      - dev

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    uses: certego/.github/.github/workflows/detect_changes.yml@develop
    with:
      backend_directories: backend
      frontend_directories: frontend

  python:
    if: ${{ needs.detect-changes.outputs.backend > 0 }}
    needs: detect-changes
    uses: certego/.github/.github/workflows/python.yml@develop
    with:
      working_directory: backend

      use_black: true
      use_isort: true
      use_flake8: true
      use_pylint: true
      use_bandit: false

      requirements_path: backend/requirements.txt
      packages_path: backend/packages.txt

      django_settings_module: backend.settings

      custom_command: whoami

      check_migrations: true
      check_requirements_licenses: true
      check_docs_directory: docs
      check_dockerfile: Dockerfile

      use_postgres: true
      use_memcached: false
      use_elastic_search: false
      use_rabbitmq: false
      use_mongo: false
      use_celery: true


      use_coverage: true
      upload_coverage: true

      tags_for_slow_tests: slow
      tags_for_manual_tests: manual

      postgres_db: db
      postgres_user: user
      postgres_password: password
      celery_app: backend.celery
      celery_queues: default

      env: >-
        {"KEY": "VALUE"}
      python_versions: >-
        [ "3.9", "3.10" ]

  node:
    if: ${{ needs.detect-changes.outputs.frontend > 0 }}
    needs: detect-changes
    uses: certego/.github/.github/workflows/node.yml@develop
    with:
      working_directory: frontend

      use_eslint: true
      use_stylelint: true
      use_prettier: true

      check_packages_licenses: true
      use_jest: true
      use_coverage: true
      upload_coverage: true
      node_versions: >-
        [ "16", "17", "18" ]

  release_and_tag:
    uses: certego/.github/.github/workflows/release_and_tag.yml@develop
    secrets: inherit
    with:
      publish_on_pypi: false # Token should be set on secret PYPI_API_TOKEN
      publish_on_test_pypi: false # Token should be set on secret TEST_PYPI_API_TOKEN
      publish_on_npm: false # Token should be set on secret NPM_API_TOKEN
