name: 'Python installation'
description: 'Python installation'

runs:
  using: "composite"
  steps:
    - run: echo Hello.
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
