name: Reusable detect changes workflow
on:
  workflow_call:
    inputs:
      backend_directories:
        description: Backend directories separated by spaces
        required: false
        type: string
      
      backend_exclusions:
        description: Backend directories or files to be excluded separated by spaces
        required: false
        type: string

      frontend_directories:
        description: Frontend directories separated by spaces
        required: false
        type: string
      
      frontend_exclusions:
        description: Frontend directories or files to be excluded separated by spaces
        required: false
        type: string

      ubuntu_version:
        description: Ubuntu version to use
        type: string
        default: latest
        required: false

    outputs:
      backend:
        description: Number of files changed in backend
        value: ${{ jobs.detect-changes.outputs.backend }}

      frontend:
        description: Number of files changed in frontend
        value: ${{ jobs.detect-changes.outputs.frontend }}

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-${{ inputs.ubuntu_version }}
    outputs:
      backend: ${{steps.diff_check_backend.outputs.backend}}
      frontend: ${{steps.diff_check_frontend.outputs.frontend}}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}

    - uses: actions/checkout@v4
      with:
        clean: false
    - name: Generate summary
      if: ${{inputs.backend_directories != ''}} | ${{inputs.frontend_directories != ''}}
      run: |
        echo "### Detect Changes summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

    - name: Generate diffs for backend
      if: ${{inputs.backend_directories != ''}}
      id: diff_check_backend
      run: |
        BACKEND_EXCLUSIONS=""
        if ${{ inputs.backend_exclusions != ''}}; then
          for exclusion in ${{ inputs.backend_exclusions }}; do
            BACKEND_EXCLUSIONS+=":(glob,exclude)$exclusion "
          done
        fi
        # No need to add other quotes since they will already be added.
        BACKEND_CHANGES=$(git diff --compact-summary origin/${{ github.base_ref }} -- ${{ inputs.backend_directories }} $BACKEND_EXCLUSIONS | head -n -1 | wc -l)
        echo "backend=$BACKEND_CHANGES" >> $GITHUB_OUTPUT
        echo "Backend Changes: $BACKEND_CHANGES" >> $GITHUB_STEP_SUMMARY
        echo "::debug::diff command:git diff --compact-summary origin/${{ github.base_ref }} -- ${{ inputs.backend_directories }} $BACKEND_EXCLUSIONS"
        echo "::debug::diff command results: $(git diff --compact-summary origin/${{ github.base_ref }} -- ${{ inputs.backend_directories }} $BACKEND_EXCLUSIONS | head -n -1 )"
        echo "backend $BACKEND_CHANGES"


    - name: Generate diffs for frontend
      if: ${{inputs.frontend_directories != ''}}
      id: diff_check_frontend
      run: |
        FRONTEND_EXCLUSIONS=""
        if ${{ inputs.frontend_exclusions != ''}}; then
          for exclusion in ${{ inputs.frontend_exclusions }}; do
            FRONTEND_EXCLUSIONS+=":(glob,exclude)$exclusion "
          done
        fi
        FRONTEND_CHANGES=$(git diff --compact-summary origin/${{ github.base_ref }} -- ${{ inputs.frontend_directories }} $FRONTEND_EXCLUSIONS | head -n -1 | wc -l)
        echo "frontend=$FRONTEND_CHANGES" >> $GITHUB_OUTPUT
        echo "Frontend Changes: $FRONTEND_CHANGES" >> $GITHUB_STEP_SUMMARY
        echo "::debug::diff command:git diff --compact-summary origin/${{ github.base_ref }} -- ${{ inputs.backend_directories }} $FRONTEND_EXCLUSIONS"
        echo "::debug::diff command results: $(git diff --compact-summary origin/${{ github.base_ref }} -- ${{ inputs.backend_directories }} $FRONTEND_EXCLUSIONS | head -n -1 )"
        echo "frontend $FRONTEND_CHANGES"

