name: Reusable detect changes workflow
on:
  workflow_call:
    inputs:
      backend_directories:
        description: Backend directories separated by spaces
        required: false
        type: string
        default: ''

      frontend_directories:
        description: Frontend directories separated by spaces
        required: false
        type: string
        default: ''

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{steps.diff_check.outputs.backend}}
      frontend: ${{steps.diff_check.outputs.frontend}}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}

    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Generate diffs for backend
      if: ${{inputs.backend_directories}} != ''
      id: diff_check_backend
      run: |
        git branch -a --list | cat
        BACKEND_CHANGES=$(git diff --compact-summary origin/${{ github.base_ref }} -- ${{ inputs.backend_directories }} | head -n -1 | wc -l)
        echo "::set-output name=backend::$BACKEND_CHANGES"

    - name: Generate diffs for frontend
      if: ${{inputs.frontend_directories}} != ''
      id: diff_check_frontend
      run: |
        git branch -a --list | cat
        FRONTEND_CHANGES=$(git diff --compact-summary origin/${{ github.base_ref }} -- ${{ inputs.frontend_directories }} | head -n -1 | wc -l)
        echo "::set-output name=frontend::$FRONTEND_CHANGES"
