name: Reusable node linter workflow
on:
  workflow_call:
    inputs:
      node_versions:
        description: Node versions to use
        type: string
        required: true
      working_directory:
        description: Directory that must be run against the linters
        type: string
        required: true

      use_eslint:
        description: Use eslint formatter
        default: true
        type: boolean
        required: false
      use_prettier:
        description: Use prettier formatter
        default: true
        type: boolean
        required: false
      use_stylelint:
        description: Use stylelint formatter
        default: true
        type: boolean
        required: false


jobs:
    linters:
        name: Run node.js linters
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: ${{ fromJson(inputs.node_versions) }}
        steps:
          - uses: actions/checkout@v3

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node_version }}
              cache: 'npm'
              cache-dependency-path: ${{ inputs.working_directory }}/package-lock.json

          - name: Install dependencies
            run: |
              npm ci
            working-directory: ${{ inputs.working_directory }}

          - name: Lint with eslint
            if: ${{ inputs.use_eslint }}
            run: |
              npm run lint
            working-directory: ${{ inputs.working_directory }}

          - name: Lint with prettier
            if: ${{ inputs.use_prettier }}
            run: |
              npm run prettier:check
            working-directory: ${{ inputs.working_directory }}

          - name: Lint with stylelint
            if: ${{ inputs.use_stylelint }}
            run: |
              npm run lint-sass
            working-directory: ${{ inputs.working_directory }}
