name: Composite action node linter
inputs:
  working_directory:
    description: Path to the package.json file
    type: string
    required: true


  use_jest:
    description: Use jest suite
    type: boolean
    required: true
  use_coverage:
    description: Output coverage. Require jest to be set.
    type: boolean
    required: true
  upload_coverage:
    description: Upload coverage report to GitHub
    type: boolean
    required: true


runs:
  using: "composite"
  steps:
    - name: Run jest tests
      if: ${{ inputs.use_jest }}
      id: jest-tests
      run: |
        if [[ '${{ inputs.use_coverage }}' != 'false' ]]; then
          CMD="npm test -- --silent --coverage"
        else
            CMD="npm test"
        fi
        echo "Running command: ${CMD}"
        if [[ '${{ inputs.use_coverage }}' != 'false' ]] && [[ '${{ inputs.upload_coverage }}' != 'false' ]]; then
          echo ::set-output name=coverage_content::$($CMD | grep -Ev "^(>|$)" | awk '{printf "%s<br />", $0}')
        else
          $CMD
        fi
      working-directory: ${{ inputs.working_directory }}

    - name: Find Comment
      if: inputs.use_coverage && inputs.upload_coverage
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Jest coverage report
        direction: first

    - name: Create or update coverage to PR comment
      if: inputs.use_coverage && inputs.upload_coverage
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Jest coverage report:
          ${{ steps.jest-tests.outputs.coverage_content }}
        edit-mode: replace