name: Ci

on:
  pull_request:
    branches:
      - master
      - main
      - develop
      - dev

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  node_linters:
    uses: ./.github/workflows/node_linter.yml
    with:
      working_directory: test/node_test
      use_eslint: true
      use_prettier: true
      use_stylelint: true
      node_versions: >-
        ["16"]

  node_tests:
    uses: ./.github/workflows/node_tests.yml
    with:
      working_directory: test/node_test
      use_jest: true
      node_versions: >-
        ["16"]

  python_linters:
    uses: ./.github/workflows/python_linter.yml
    with:
      working_directory: test/python_test
      use_black: true
      use_isort: true
      use_flake8: true
      use_pylint: true
      use_bandit: true
      python_versions: >-
        ["3.9"]

  python_tests:
     uses: ./.github/workflows/python_tests.yml
     with:
      working_directory: test/python_test
      requirements_path: test/python_test/requirements.txt
      packages_path: test/python_test/packages.txt
      django_settings_module: python_test.settings
      check_migrations: true

      use_postgres: true
      use_memcached: false
      use_elastic_search: false
      use_rabbitmq: true

      use_pytest: true
      use_unittest: true
      use_coverage: true
      upload_coverage: false
      custom_command: whoami; ls -la
      python_versions: >-
        ["3.9"]
