name: Composite action python linter
description: Composite action python linter
inputs:
  working_directory:
    description: Directory that must be run against the linters
    type: string
    required: true

  use_black:
    description: Use black formatter
    type: boolean
    required: true
  use_isort:
    description: Use isort formatter
    type: boolean
    required: true
  use_flake8:
    description: Use flake8 linter
    type: boolean
    required: true
  use_pylint:
    description: Use pylint linter
    type: boolean
    required: true
  use_bandit:
    description: Use bandit linter
    type: boolean
    required: true

  bandit_config_file:
    description: Path to the bandit config file from the working dir
    type: string
    required: true

runs:
  using: "composite"
  steps:

    - name: Black formatter
      if: ${{ inputs.use_black }}
      run:
        black . --check --diff
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Lint with flake8 (PEP8 enforcer + linter)
      if: ${{ inputs.use_flake8 }}
      run: |
        flake8 .  --show-source
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: isort
      if: ${{ inputs.use_isort }}
      run: |
        CMD="isort . --filter-files --check-only --diff"
        if [[ '${{ inputs.use_black }}' != 'false' ]]; then
          CMD="$CMD --profile black"
        fi
        echo "Executing $CMD"
        $CMD
      working-directory: ${{ inputs.working_directory }}
      shell: bash


    - name: bandit
      if: ${{ inputs.use_bandit }}
      run: |
        bandit . -r -c ${{ inputs.bandit_config_file }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash