name: Composite action python linter
description: Composite action python linter
inputs:
  working_directory:
    description: Directory that must be run against the linters
    required: true

  use_black:
    description: Use black formatter
    required: true
  use_isort:
    description: Use isort formatter
    required: true
  use_flake8:
    description: Use flake8 linter
    required: true
  use_pylint:
    description: Use pylint linter
    required: true
  use_bandit:
    description: Use bandit linter
    required: true

  bandit_config_file:
    description: Path to the bandit config file from the working dir
    required: true

runs:
  using: "composite"
  steps:
    - name: Black formatter
      run:
        if [[ ${{ inputs.use_black }} != 'false' ]]; then
          black . --check --diff
        fi
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Lint with flake8 (PEP8 enforcer + linter)
      run: |
        if [[ ${{inputs.use_flake8 }} != 'false' ]]; then
          flake8 .  --show-source
        fi
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: isort
      run: |
        if [[ ${{inputs.use_isort }} != 'false' ]]; then
          CMD="isort . --filter-files --check-only --diff"
          if [[ '${{ inputs.use_black }}' != 'false' ]]; then
            CMD="$CMD --profile black"
          fi
          echo "Executing $CMD"
          $CMD
        fi

      working-directory: ${{ inputs.working_directory }}
      shell: bash


    - name: bandit
      run: |
        if [[ ${{inputs.use_bandit }} != 'false' ]]; then
          bandit . -r -c ${{ inputs.bandit_config_file }}
        fi
      working-directory: ${{ inputs.working_directory }}
      shell: bash