name: Reusable node linter workflow
on:
  workflow_call:
    inputs:
      package_lock_path:
        description: Path to the package.lock file
        type: string
        required: true
      node_version:
        description: Node version to use
        type: string
        required: true
      directory_to_lint:
        description: Directory that must be run against the linters
        type: string
        required: true

      use_eslint:
        description: Use eslint formatter
        default: true
        type: boolean
        required: false
      use_prettier:
        description: Use prettier formatter
        default: true
        type: boolean
        required: false
      use_stylelint:
        description: Use stylelint formatter
        default: true
        type: boolean
        required: false


jobs:
    linters:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Set up NodeJS
            uses: actions/setup-node@v3
            with:
              node-version: ${{ inputs.node_version }}

          - name: Cache node modules
            uses: actions/cache@v3
            with:
              path: ~/.npm
              key: npm-build-${{ hashFiles(input.package_lock_path) }}
              restore-keys: |
                npm-build-${{ hashFiles(input.package_lock_path) }}
                npm-build-
                npm

          - name: Install dependencies
            run: |
              npm i --no-optional --no-audit --no-fund

            working-directory: ./frontend
          - name: Lint with eslint
            if: ${{ inputs.use_eslint }}
            run: |
              npm run lint
            working-directory: ${{ inputs.directory_to_lint }}

          - name: Lint with prettier
            if: ${{ inputs.use_prettier }}
            run: |
              npm run prettier:check ${{ inputs.directory_to_lint }}
            working-directory: ${{ inputs.directory_to_lint }}

          - name: Lint with stylelint
            if: ${{ inputs.use_stylelint }}
            run: |
              npm run prettier:stylelint-check
            working-directory: ${{ inputs.directory_to_lint }}
